# Generated by Django 5.0.3 on 2024-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment_user_reservation_user_alter_reservation_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
