# Generated by Django 5.0.3 on 2024-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_park_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
