# Generated by Django 5.0.3 on 2024-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reservation_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='park',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
